import type { EmailAnalysis, EmailThread, ExecutiveEmail } from "./types";

// All timestamps are generated relative to "now" so the demo always looks live.
function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 3600_000).toISOString();
}
function daysAgo(d: number, hour = 9): string {
  const t = new Date();
  t.setDate(t.getDate() - d);
  t.setHours(hour, 15, 0, 0);
  return t.toISOString();
}
function todayAt(hour: number): string {
  const t = new Date();
  t.setHours(hour, 0, 0, 0);
  return t.toISOString();
}
function inDays(d: number, hour = 17): string {
  const t = new Date();
  t.setDate(t.getDate() + d);
  t.setHours(hour, 0, 0, 0);
  return t.toISOString();
}

export const MOCK_EMAILS: ExecutiveEmail[] = [
  {
    id: "em-01",
    threadId: "th-01",
    senderName: "Sarah Lee",
    senderEmail: "sarah.lee@example.com",
    senderRole: "VP Finance",
    subject: "Approval needed: Revised Q3 hiring plan",
    receivedAt: hoursAgo(2),
    priority: "high",
    category: "needs_decision",
    summary:
      "Finance is asking you to approve the revised Q3 hiring plan — three roles, one of which now starts earlier than originally budgeted.",
    request: "Approve three roles by Friday 5 PM.",
    deadline: inDays(2, 17),
    recommendedAction: "Review the start dates in the attachment before approving.",
    confidence: 0.91,
    attachmentCount: 1,
    unread: true,
    completed: false,
  },
  {
    id: "em-02",
    threadId: "th-02",
    senderName: "Marcus Webb",
    senderEmail: "marcus.webb@example.com",
    senderRole: "Head of Client Success",
    subject: "URGENT: Meridian account threatening to leave",
    receivedAt: hoursAgo(1),
    priority: "critical",
    category: "needs_response",
    summary:
      "Your second-largest client is escalating after two missed service commitments and has asked to speak with you directly before Thursday.",
    request: "Call the client sponsor personally before Thursday.",
    deadline: inDays(1, 12),
    recommendedAction: "Call Dana Ferro today; Marcus has prepared a briefing doc.",
    confidence: 0.94,
    attachmentCount: 1,
    unread: true,
    completed: false,
  },
  {
    id: "em-03",
    threadId: "th-03",
    senderName: "Priya Nair",
    senderEmail: "priya.nair@example.com",
    senderRole: "COO",
    subject: "Weekly ops update — all green except onboarding backlog",
    receivedAt: hoursAgo(4),
    priority: "medium",
    category: "important",
    summary:
      "Operations are on track overall; onboarding backlog grew 12% and Priya is already adding temp capacity. No action needed from you.",
    request: "No response required — awareness only.",
    recommendedAction: "Note the onboarding backlog trend; no reply needed.",
    confidence: 0.88,
    attachmentCount: 0,
    unread: true,
    completed: false,
  },
  {
    id: "em-04",
    threadId: "th-04",
    senderName: "Tom Askew",
    senderEmail: "tom.askew@example.com",
    senderRole: "Events Coordinator, FinServ Summit",
    subject: "Speaker slot confirmation + AV requirements form",
    receivedAt: hoursAgo(7),
    priority: "low",
    category: "delegatable",
    summary:
      "The conference needs your AV requirements and headshot by next week. Entirely handleable by your EA or comms team.",
    request: "Return the AV form and a headshot by next Wednesday.",
    deadline: inDays(6, 17),
    recommendedAction: "Delegate to your executive assistant.",
    confidence: 0.9,
    attachmentCount: 2,
    unread: true,
    completed: false,
  },
  {
    id: "em-05",
    threadId: "th-05",
    senderName: "Elena Ruiz",
    senderEmail: "elena.ruiz@example.com",
    senderRole: "Board Chair",
    subject: "30 minutes before the board meeting?",
    receivedAt: hoursAgo(3),
    priority: "high",
    category: "needs_response",
    summary:
      "The board chair wants 30 minutes with you before next week's board meeting to align on the capital allocation discussion.",
    request: "Confirm a 30-minute slot before Tuesday's board meeting.",
    deadline: inDays(4, 10),
    recommendedAction: "Offer Monday afternoon; she flagged capital allocation as the topic.",
    confidence: 0.92,
    attachmentCount: 0,
    unread: true,
    completed: false,
  },
  {
    id: "em-06",
    threadId: "th-06",
    senderName: "David Chen",
    senderEmail: "david.chen@example.com",
    senderRole: "General Counsel",
    subject: "Vendor master agreement — redlines for your review",
    receivedAt: hoursAgo(22),
    priority: "high",
    category: "needs_decision",
    summary:
      "Legal has finished redlining the vendor master agreement. Two changed clauses shift liability terms and need your sign-off before countersigning.",
    request: "Approve the liability cap change and the 60-day termination clause.",
    deadline: inDays(3, 17),
    recommendedAction: "Read sections 7.2 and 11.4 in the attachment before approving.",
    confidence: 0.89,
    attachmentCount: 1,
    unread: true,
    completed: false,
  },
  {
    id: "em-07",
    threadId: "th-07",
    senderName: "Janet Moore",
    senderEmail: "janet.moore@example.com",
    senderRole: "VP People",
    subject: "Benefits renewal update and a few housekeeping items",
    receivedAt: daysAgo(1, 16),
    priority: "high",
    category: "important",
    summary:
      "Reads like routine housekeeping, but paragraph three contains a hard deadline: the benefits carrier needs a signed renewal today to hold current rates.",
    request: "Sign the benefits renewal by end of day today to lock rates.",
    deadline: todayAt(17),
    recommendedAction: "Sign today — missing it triggers an 8% premium increase.",
    confidence: 0.86,
    attachmentCount: 1,
    unread: true,
    completed: false,
  },
  {
    id: "em-08",
    threadId: "th-08",
    senderName: "Rob Vance",
    senderEmail: "rob.vance@example.com",
    senderRole: "VP Corporate Development",
    subject: "Re: Re: Re: Northgate acquisition model v4",
    receivedAt: hoursAgo(5),
    priority: "high",
    category: "needs_decision",
    summary:
      "Fourth revision of the acquisition model. Rob quietly changed the retention assumption from 92% to 85% since the version you saw, which moves payback from 3.1 to 4.2 years.",
    request: "Confirm whether to proceed to a letter of intent at the new assumptions.",
    deadline: inDays(5, 17),
    recommendedAction: "Ask why retention dropped before green-lighting the LOI.",
    confidence: 0.83,
    attachmentCount: 1,
    unread: true,
    completed: false,
  },
  {
    id: "em-09",
    threadId: "th-09",
    senderName: "Industry Weekly",
    senderEmail: "digest@example-news.com",
    subject: "This week in wealth management — 5 stories",
    receivedAt: daysAgo(1, 7),
    priority: "low",
    category: "low_priority",
    summary: "Weekly industry newsletter. One story mentions a competitor's fee cut; otherwise routine.",
    request: "Nothing — optional reading.",
    recommendedAction: "Skim the competitor fee-cut story if time allows.",
    confidence: 0.95,
    attachmentCount: 0,
    unread: true,
    completed: false,
  },
  {
    id: "em-10",
    threadId: "th-10",
    senderName: "Janet Moore",
    senderEmail: "janet.moore@example.com",
    senderRole: "VP People",
    subject: "Confidential: senior leadership matter",
    receivedAt: hoursAgo(6),
    priority: "critical",
    category: "needs_response",
    summary:
      "A confidential personnel matter involving a senior leader requires your guidance on next steps before HR proceeds. Legal is already copied.",
    request: "Reply with direction on which of two options HR should take.",
    deadline: inDays(1, 17),
    recommendedAction: "Speak with Janet and David Chen live rather than in writing.",
    confidence: 0.87,
    attachmentCount: 0,
    unread: true,
    completed: false,
  },
  {
    id: "em-11",
    threadId: "th-11",
    senderName: "David Chen",
    senderEmail: "david.chen@example.com",
    senderRole: "General Counsel",
    subject: "Re: Office lease renewal — status",
    receivedAt: daysAgo(2, 11),
    priority: "medium",
    category: "waiting",
    summary:
      "You asked legal to review the HQ lease renewal terms. David confirmed he'll have the analysis to you by Thursday — no action needed until then.",
    request: "None yet — awaiting legal's analysis, promised Thursday.",
    recommendedAction: "Wait; follow up Friday if the analysis hasn't arrived.",
    confidence: 0.93,
    attachmentCount: 0,
    unread: false,
    completed: false,
  },
];

export const MOCK_THREADS: Record<string, EmailThread> = {
  "th-01": {
    threadId: "th-01",
    subject: "Approval needed: Revised Q3 hiring plan",
    messages: [
      {
        id: "th-01-m1",
        from: "You",
        fromEmail: "ceo@example.com",
        sentAt: daysAgo(4, 15),
        body: "Sarah — the original plan is over budget for Q3. Please revise and send me a version I can approve by Friday.",
      },
      {
        id: "th-01-m2",
        from: "Sarah Lee",
        fromEmail: "sarah.lee@example.com",
        sentAt: hoursAgo(2),
        body: "Hi,\n\nAttached is the revised Q3 hiring plan reflecting the budget conversation from Monday's leadership meeting. We reduced the ask from five roles to three: Senior Advisor (Sacramento), Ops Analyst, and Marketing Manager.\n\nOne note — to secure the Senior Advisor candidate we moved her start date up to August 4, which is technically two weeks before the approved budget period begins. Finance can absorb it, but I wanted it on your radar rather than buried in the spreadsheet.\n\nThe full forecast detail is in the attached workbook (second tab has the sensitivity analysis).\n\nCould you approve the three roles by Friday 5 PM so recruiting can extend offers Monday?\n\nThanks,\nSarah",
      },
    ],
  },
  "th-02": {
    threadId: "th-02",
    subject: "URGENT: Meridian account threatening to leave",
    messages: [
      {
        id: "th-02-m1",
        from: "Marcus Webb",
        fromEmail: "marcus.webb@example.com",
        sentAt: hoursAgo(1),
        body: "I need to flag this immediately.\n\nDana Ferro at Meridian Group called me this morning. They are formally evaluating alternatives after we missed the quarterly reporting deadline twice and the portal migration slipped again. Meridian is our second-largest relationship (~$340M).\n\nDana said, quote: \"If I don't hear from your CEO before Thursday, we're moving to an RFP.\"\n\nI've attached a one-page briefing with the full timeline of the service misses, what we've already offered, and Dana's likely asks. My honest read: this is recoverable, but only with a personal call from you — another apology from my team will make it worse.\n\nI'm free anytime today to prep you. — Marcus",
      },
    ],
  },
  "th-03": {
    threadId: "th-03",
    subject: "Weekly ops update — all green except onboarding backlog",
    messages: [
      {
        id: "th-03-m1",
        from: "Priya Nair",
        fromEmail: "priya.nair@example.com",
        sentAt: hoursAgo(4),
        body: "Weekly summary — no action needed from you.\n\n• Service levels: 98.2% within SLA (target 97%)\n• Trading ops: clean week, zero exceptions outstanding\n• Onboarding: backlog grew 12% week-over-week due to the two advisor teams that joined this month. I've approved two temp hires and expect the backlog back to normal within three weeks.\n• Facilities: Denver office move on schedule\n\nI'll flag onboarding again next week only if the trend doesn't reverse.\n\nPriya",
      },
    ],
  },
  "th-04": {
    threadId: "th-04",
    subject: "Speaker slot confirmation + AV requirements form",
    messages: [
      {
        id: "th-04-m1",
        from: "Tom Askew",
        fromEmail: "tom.askew@example.com",
        sentAt: hoursAgo(7),
        body: "Dear speaker,\n\nThank you for confirming your keynote at FinServ Summit. To finalize logistics we need:\n\n1. Completed AV requirements form (attached)\n2. A high-resolution headshot\n3. Your final session title (30 words max)\n\nPlease return these by next Wednesday so we can print the program on schedule.\n\nBest regards,\nTom Askew\nEvents Coordinator",
      },
    ],
  },
  "th-05": {
    threadId: "th-05",
    subject: "30 minutes before the board meeting?",
    messages: [
      {
        id: "th-05-m1",
        from: "Elena Ruiz",
        fromEmail: "elena.ruiz@example.com",
        sentAt: hoursAgo(3),
        body: "Before Tuesday's board meeting I'd like 30 minutes with you, ideally Monday.\n\nTwo of the independent directors have questions about the capital allocation plan — specifically the split between the acquisition pipeline and the technology investment. I'd rather we walk in aligned than debate it live in the meeting.\n\nDoes Monday afternoon work?\n\nElena",
      },
    ],
  },
  "th-06": {
    threadId: "th-06",
    subject: "Vendor master agreement — redlines for your review",
    messages: [
      {
        id: "th-06-m1",
        from: "David Chen",
        fromEmail: "david.chen@example.com",
        sentAt: hoursAgo(22),
        body: "Attached are the final redlines on the vendor master agreement.\n\nTwo changes need your explicit sign-off before I countersign:\n\n1. Section 7.2 — liability cap raised from 1x to 2x annual fees (their ask; I recommend accepting, it's market standard).\n2. Section 11.4 — termination notice shortened from 90 to 60 days (our ask; they accepted).\n\nEverything else is cosmetic. If you approve both, I can execute by end of week and we keep the implementation timeline.\n\nDavid",
      },
    ],
  },
  "th-07": {
    threadId: "th-07",
    subject: "Benefits renewal update and a few housekeeping items",
    messages: [
      {
        id: "th-07-m1",
        from: "Janet Moore",
        fromEmail: "janet.moore@example.com",
        sentAt: daysAgo(1, 16),
        body: "A few People-team updates:\n\nFirst, the engagement survey closes Friday — participation is at 71%, tracking ahead of last year.\n\nSecond, we finalized the summer intern conversion offers; four of six accepted.\n\nThird, on the benefits renewal: the carrier came back better than expected — a 3% increase instead of the 8% we budgeted. The catch is that the rate hold expires today; they need your signature on the renewal letter (attached) by end of business today or we revert to the 8% quote. Sorry for the short fuse — their underwriter only confirmed this morning.\n\nLastly, the new parental leave policy draft will come to you next week.\n\nJanet",
      },
    ],
  },
  "th-08": {
    threadId: "th-08",
    subject: "Northgate acquisition model v4",
    messages: [
      {
        id: "th-08-m1",
        from: "Rob Vance",
        fromEmail: "rob.vance@example.com",
        sentAt: daysAgo(6, 10),
        body: "First pass at the Northgate model attached (v1). Headline: $58M purchase price, 92% client retention assumption, payback in 3.1 years. Happy to walk through it.",
      },
      {
        id: "th-08-m2",
        from: "You",
        fromEmail: "ceo@example.com",
        sentAt: daysAgo(5, 14),
        body: "Numbers look workable at 92% retention. Pressure-test that assumption with the diligence data and come back with a final view. If it holds, I'm inclined to move to an LOI.",
      },
      {
        id: "th-08-m3",
        from: "Rob Vance",
        fromEmail: "rob.vance@example.com",
        sentAt: daysAgo(2, 9),
        body: "v3 attached — incorporated the diligence findings on their fee schedule and updated the synergy timeline. Still targeting LOI discussion this week.",
      },
      {
        id: "th-08-m4",
        from: "Rob Vance",
        fromEmail: "rob.vance@example.com",
        sentAt: hoursAgo(5),
        body: "v4 attached, hopefully final. Cleaned up the synergy phasing and refreshed the comps.\n\nNote we're now carrying retention at 85% based on the client concentration data from diligence — two of their top ten households indicated they may not transition. Payback moves to 4.2 years at the revised assumption.\n\nAssuming you're comfortable, I'd like to schedule the LOI conversation with their bankers for early next week. Can you confirm by Friday?\n\nRob",
      },
    ],
  },
  "th-09": {
    threadId: "th-09",
    subject: "This week in wealth management — 5 stories",
    messages: [
      {
        id: "th-09-m1",
        from: "Industry Weekly",
        fromEmail: "digest@example-news.com",
        sentAt: daysAgo(1, 7),
        body: "This week's top stories:\n\n1. Regional RIA consolidation continues as two mid-market firms merge\n2. Competitor announces 15% fee reduction on accounts under $500K\n3. SEC releases updated marketing rule FAQ\n4. Survey: 62% of clients under 45 want digital-first planning\n5. Rate outlook: strategists split on next quarter\n\nRead online for full stories.",
      },
    ],
  },
  "th-10": {
    threadId: "th-10",
    subject: "Confidential: senior leadership matter",
    messages: [
      {
        id: "th-10-m1",
        from: "Janet Moore",
        fromEmail: "janet.moore@example.com",
        sentAt: hoursAgo(6),
        body: "This is confidential — please limit forwarding.\n\nWe've completed the review of the complaint involving a member of the senior leadership team that I briefed you on last week. The findings substantiate part of the complaint. David is copied and agrees on the legal posture.\n\nWe need your direction between two paths:\n\nOption A: formal corrective action with a documented improvement plan.\nOption B: negotiated transition with a separation agreement.\n\nBoth are defensible. We'd like your read before HR proceeds — ideally by tomorrow evening, as the complainant is expecting an update Friday.\n\nGiven the sensitivity, happy to discuss live instead of email.\n\nJanet",
      },
    ],
  },
  "th-11": {
    threadId: "th-11",
    subject: "Office lease renewal — status",
    messages: [
      {
        id: "th-11-m1",
        from: "You",
        fromEmail: "ceo@example.com",
        sentAt: daysAgo(3, 9),
        body: "David — before we commit to the 7-year HQ renewal, I want your read on the early-termination and sublease clauses. When can you have that?",
      },
      {
        id: "th-11-m2",
        from: "David Chen",
        fromEmail: "david.chen@example.com",
        sentAt: daysAgo(2, 11),
        body: "On it. The landlord's draft has an unusual sublease consent standard I want outside counsel to sanity-check. I'll have the full analysis to you by Thursday.\n\nDavid",
      },
    ],
  },
};

export const MOCK_ANALYSES: Record<string, EmailAnalysis> = {
  "em-01": {
    category: "needs_decision",
    priority: "high",
    summary:
      "Finance is asking for approval of the revised Q3 hiring plan — reduced from five roles to three after Monday's budget discussion.",
    request: "Approve three roles by Friday 5 PM so recruiting can extend offers Monday.",
    recommended_action: "Review the August 4 start date before approving — it precedes the approved budget period.",
    why_it_matters:
      "You asked for this revision yourself, offers are staged behind your approval, and one start date quietly breaches the budget window you set.",
    deadline: inDays(2, 17),
    risks: ["The Senior Advisor role starts August 4 — two weeks before the approved budget period begins."],
    missing_context: [
      "The attached workbook's second tab contains a sensitivity analysis not summarized in the email body.",
      "The role count changed from five (previous thread) to three — the two cut roles aren't named.",
    ],
    key_people: [{ name: "Sarah Lee", role: "VP Finance" }],
    commitments: ["You asked Sarah on Monday for a revised version you could approve by Friday."],
    attachments: [{ name: "Q3_Hiring_Plan_v2.xlsx", needs_review: true }],
    suggested_reply_intents: ["approve", "ask_question", "schedule"],
    confidence: 0.91,
  },
  "em-02": {
    category: "needs_response",
    priority: "critical",
    summary:
      "Meridian Group (~$340M, second-largest client) is threatening an RFP after two missed reporting deadlines and a slipped portal migration.",
    request: "Dana Ferro expects a personal call from you before Thursday.",
    recommended_action: "Call Dana today after a 15-minute prep with Marcus; don't send another written apology.",
    why_it_matters:
      "Losing this relationship would be a material revenue event, and the client has explicitly made you — not the account team — the condition for staying.",
    deadline: inDays(1, 12),
    risks: [
      "Client explicitly stated they move to RFP without CEO contact by Thursday.",
      "Marcus assesses that another team-level apology will make the situation worse.",
    ],
    missing_context: [
      "The attached briefing contains the full timeline of service misses and what has already been offered — the email body doesn't list the prior concessions.",
      "Dana's 'likely asks' in the attachment may include fee concessions not mentioned in the email.",
    ],
    key_people: [
      { name: "Dana Ferro", role: "Client sponsor, Meridian Group" },
      { name: "Marcus Webb", role: "Head of Client Success" },
    ],
    commitments: [],
    attachments: [{ name: "Meridian_Briefing.pdf", needs_review: true }],
    suggested_reply_intents: ["acknowledge", "schedule", "ask_question"],
    confidence: 0.94,
  },
  "em-03": {
    category: "important",
    priority: "medium",
    summary: "Weekly ops update: all metrics green except onboarding backlog, up 12% — mitigation already underway.",
    request: "None — explicitly informational.",
    recommended_action: "No reply needed. Watch whether onboarding appears again next week.",
    why_it_matters: "The onboarding backlog is the only degrading operational metric and relates to this month's new advisor teams.",
    risks: [],
    missing_context: [
      "Priya will only re-flag onboarding if the trend doesn't reverse — silence next week means resolved, not forgotten.",
    ],
    key_people: [{ name: "Priya Nair", role: "COO" }],
    commitments: [],
    attachments: [],
    suggested_reply_intents: ["acknowledge", "custom"],
    confidence: 0.88,
  },
  "em-04": {
    category: "delegatable",
    priority: "low",
    summary: "Conference logistics: AV form, headshot, and session title due next Wednesday for your confirmed keynote.",
    request: "Return the AV form, headshot, and a 30-word session title by Wednesday.",
    recommended_action: "Delegate to your EA; only the session title needs your input.",
    why_it_matters: "Low stakes, but missing the deadline affects printed materials for a keynote you're giving.",
    deadline: inDays(6, 17),
    risks: [],
    missing_context: ["The session title (30 words max) is the one item that genuinely needs your voice — the rest is administrative."],
    key_people: [{ name: "Tom Askew", role: "Events Coordinator, FinServ Summit" }],
    commitments: ["You previously confirmed this keynote."],
    attachments: [
      { name: "AV_Requirements_Form.pdf", needs_review: false },
      { name: "Speaker_Guidelines.pdf", needs_review: false },
    ],
    suggested_reply_intents: ["delegate", "acknowledge"],
    confidence: 0.9,
  },
  "em-05": {
    category: "needs_response",
    priority: "high",
    summary: "Board chair requests 30 minutes before Tuesday's meeting to align on capital allocation questions from two independent directors.",
    request: "Confirm a 30-minute slot, ideally Monday afternoon.",
    recommended_action: "Accept Monday and ask which directors raised questions so you can prepare targeted answers.",
    why_it_matters:
      "Two independent directors questioning the acquisition-vs-technology split before a board meeting is an alignment risk worth defusing early.",
    deadline: inDays(4, 10),
    risks: ["Walking into the board meeting unaligned on capital allocation could turn a routine agenda item into a live debate."],
    missing_context: [
      "Elena doesn't name which two directors have questions.",
      "The concern is specifically the split between the acquisition pipeline and technology investment — relevant to the pending Northgate decision in a separate thread.",
    ],
    key_people: [{ name: "Elena Ruiz", role: "Board Chair" }],
    commitments: [],
    attachments: [],
    suggested_reply_intents: ["schedule", "ask_question", "acknowledge"],
    confidence: 0.92,
  },
  "em-06": {
    category: "needs_decision",
    priority: "high",
    summary: "Legal needs your sign-off on two redlined clauses — a doubled liability cap and a shortened termination notice — to execute the vendor agreement this week.",
    request: "Approve the Section 7.2 liability change and Section 11.4 termination change.",
    recommended_action: "Read sections 7.2 and 11.4 in the redline before approving; David recommends accepting both.",
    why_it_matters: "The liability cap doubles your exposure on this vendor; delay slips the implementation timeline.",
    deadline: inDays(3, 17),
    risks: ["Section 7.2 raises the liability cap from 1x to 2x annual fees — a real increase in contractual exposure, even if market standard."],
    missing_context: [
      "The annual fee amount (which the 2x cap multiplies) isn't stated in the email — it's only in the attachment.",
      "David describes remaining changes as 'cosmetic' but they aren't enumerated.",
    ],
    key_people: [{ name: "David Chen", role: "General Counsel" }],
    commitments: [],
    attachments: [{ name: "Vendor_MSA_Redline_v3.docx", needs_review: true }],
    suggested_reply_intents: ["approve", "ask_question", "schedule"],
    confidence: 0.89,
  },
  "em-07": {
    category: "important",
    priority: "high",
    summary: "Framed as routine HR housekeeping, but it contains a same-day deadline: sign the benefits renewal today to lock a 3% increase instead of 8%.",
    request: "Sign the attached renewal letter by end of business today.",
    recommended_action: "Sign today — the rate hold expires at close of business.",
    why_it_matters: "Missing today's deadline costs roughly 5 percentage points of premium across the entire employee base for the year.",
    deadline: todayAt(17),
    risks: ["The deadline is buried in the third paragraph of an email titled 'housekeeping items' — easy to miss until the rate hold has expired."],
    missing_context: [
      "The email leads with survey and intern updates; the financially material item is third.",
      "The renewal letter itself is in the attachment, which hasn't been reviewed.",
    ],
    key_people: [{ name: "Janet Moore", role: "VP People" }],
    commitments: [],
    attachments: [{ name: "Benefits_Renewal_Letter.pdf", needs_review: true }],
    suggested_reply_intents: ["approve", "ask_question"],
    confidence: 0.86,
  },
  "em-08": {
    category: "needs_decision",
    priority: "high",
    summary: "Northgate model v4: Rob wants LOI confirmation by Friday, but the retention assumption dropped from 92% to 85% since the version you conditionally endorsed.",
    request: "Confirm by Friday whether to schedule the LOI conversation at the revised assumptions.",
    recommended_action: "Ask why retention dropped and whether price should adjust before agreeing to the LOI conversation.",
    why_it_matters:
      "Your earlier 'inclined to move' was conditioned on 92% retention holding — the economics you endorsed no longer exist (payback moved from 3.1 to 4.2 years).",
    deadline: inDays(5, 17),
    risks: [
      "Two of the target's top ten households may not transition — client concentration risk.",
      "Payback moved from 3.1 to 4.2 years, but the purchase price is unchanged at $58M.",
    ],
    missing_context: [
      "The assumption change is mentioned in passing in the fourth message of a long thread, after 'hopefully final.'",
      "Your original endorsement was explicitly conditional on the 92% assumption surviving diligence — the thread never acknowledges that condition.",
      "No revised price discussion accompanies the worsened economics.",
    ],
    key_people: [{ name: "Rob Vance", role: "VP Corporate Development" }],
    commitments: ["You said you'd move to LOI if the 92% retention assumption held after diligence."],
    attachments: [{ name: "Northgate_Model_v4.xlsx", needs_review: true }],
    suggested_reply_intents: ["ask_question", "schedule", "decline"],
    confidence: 0.83,
  },
  "em-09": {
    category: "low_priority",
    priority: "low",
    summary: "Weekly industry newsletter — five stories, none requiring action.",
    request: "None.",
    recommended_action: "Optional: skim story 2 — a competitor cut fees 15% on accounts under $500K.",
    why_it_matters: "Only marginally — the competitor fee cut could surface in client conversations.",
    risks: [],
    missing_context: ["Story 2's fee cut targets the same account segment your growth team is prioritizing this quarter."],
    key_people: [],
    commitments: [],
    attachments: [],
    suggested_reply_intents: ["custom"],
    confidence: 0.95,
  },
  "em-10": {
    category: "needs_response",
    priority: "critical",
    summary: "A substantiated complaint against a senior leader requires you to choose between corrective action and a negotiated exit by tomorrow evening.",
    request: "Direct HR to Option A (corrective action) or Option B (negotiated transition) by tomorrow evening.",
    recommended_action: "Discuss live with Janet and David rather than replying in writing — this is legally sensitive.",
    why_it_matters:
      "This decision carries legal, cultural, and reputational weight, and the complainant has been promised an update Friday.",
    deadline: inDays(1, 17),
    risks: [
      "Anything written may be discoverable — a live conversation is safer than an email reply.",
      "The complainant expects an update Friday; delay past tomorrow compresses HR's ability to execute either option properly.",
    ],
    missing_context: [
      "The email doesn't say which parts of the complaint were substantiated.",
      "Legal ('David is copied') has agreed on posture but his independent assessment isn't summarized.",
    ],
    key_people: [
      { name: "Janet Moore", role: "VP People" },
      { name: "David Chen", role: "General Counsel" },
    ],
    commitments: ["Janet briefed you on the complaint last week; the review you were told about is now complete."],
    attachments: [],
    suggested_reply_intents: ["schedule", "ask_question", "provide_decision"],
    confidence: 0.87,
  },
  "em-11": {
    category: "waiting",
    priority: "medium",
    summary: "Legal is reviewing the HQ lease renewal clauses you flagged; analysis promised by Thursday.",
    request: "None — David committed to delivering the analysis Thursday.",
    recommended_action: "Wait. Follow up Friday morning if nothing arrives.",
    why_it_matters: "The 7-year lease commitment is on hold pending this review; the landlord is waiting on your response.",
    risks: ["The landlord's draft contains an unusual sublease consent standard that outside counsel is checking."],
    missing_context: ["No landlord deadline is mentioned in this thread — worth confirming the offer doesn't expire before Thursday."],
    key_people: [{ name: "David Chen", role: "General Counsel" }],
    commitments: ["David committed to the full analysis by Thursday."],
    attachments: [],
    suggested_reply_intents: ["acknowledge", "ask_question"],
    confidence: 0.93,
  },
};

export const DELEGATE_OPTIONS = [
  { name: "Alex Park", role: "Executive Assistant" },
  { name: "Priya Nair", role: "COO" },
  { name: "Sarah Lee", role: "VP Finance" },
  { name: "Marcus Webb", role: "Head of Client Success" },
  { name: "Janet Moore", role: "VP People" },
];
